server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /wuju-pwa/ {
        try_files $uri $uri/ /wuju-pwa/index.html;
    }

    location = /wuju-pwa/sw.js {
        add_header Cache-Control "no-cache";
    }

    location ~* \.(js|css|png|json|ico)$ {
        expires 1h;
        add_header Cache-Control "public";
    }

    location = /wuju-pwa/manifest.json {
        add_header Cache-Control "no-cache";
    }
}
