server {
    listen 80;
    listen 443 ssl;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location /wuju-pwa/ {
        try_files $uri $uri/ /wuju-pwa/index.html;
    }

    location = /wuju-pwa/sw.js {
        add_header Cache-Control "no-cache";
    }

    location ~* \.(js|css|png|json|ico)$ {
        expires 1h;
        add_header Cache-Control "public";
    }

    location = /wuju-pwa/manifest.json {
        add_header Cache-Control "no-cache";
    }
}
